# Generated by Django 4.1.7 on 2023-05-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0006_auto_20200808_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='Waiting for Approval', max_length=100),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image',
            field=models.ImageField(null=True, upload_to='hotels'),
        ),
    ]
