# Generated by Django 4.1.7 on 2023-05-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0007_reservation_status_rooms_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
