# Generated by Django 4.1.7 on 2023-05-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0008_reservation_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
